POST http://localhost:3000/hotel/addHotel
Content-Type: application/json

{
    "Name" : "Test",
    "Address" : "TestAddress",
    "RoomsNumber" : "2",
    "Beds" : "al"
}
###

GET http://localhost:3000/hotel/gethotels
###

GET http://localhost:3000/
###


//Returnerer en token ved log in af admin
GET http://localhost:3000/user/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}
###
GET http://localhost:3000/user/login
Content-Type: application/json

{
    "username" : "manager",
    "password" : "manager"
}
###